stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.8-alpine
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - python setup.py install
  script:
    - PYTHONPATH=. pytest tests
  environment:
    name: test-env
  only:
    - merge_requests
    - tags


# Not executed, parent job definition
.deploy-python-tool:
  stage: deploy
  image: alpine:3.9.5
  environment:
    name: $ENVIRONMENT_NAME
  script:
    # Start ssh-agent and set identity then copy the Jar file and create a symlink
    # See https://docs.gitlab.com/ee/ci/ssh_keys/
    - apk add --update openssh-client
    - eval "$(ssh-agent)"
    - echo "$EVA_ETL_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${CLUSTER_USER}@${CLUSTER_LOGIN_NODE} "${EVA_SUBMISSION_PATH}/deploy.sh ${DEPLOY_POINT}"
  dependencies:
    - test

deploy-python-tool-development:
  extends: .deploy-python-tool
  variables:
    ENVIRONMENT_NAME: development
    EVA_SUBMISSION_PATH: $EVA_SUBMISSION_DEVELOPMENT_PATH
    DEPLOY_POINT: CI_COMMIT_BRANCH
  only:
    - merge_requests

deploy-python-tool-production:
  extends: .deploy-python-tool
  when: manual
  variables:
    ENVIRONMENT_NAME: production
    EVA_SUBMISSION_PATH: $EVA_SUBMISSION_PRODUCTION_PATH
    DEPLOY_POINT: CI_COMMIT_TAG
  only:
    - tags