ftp_dir: '/path/to/ftp/dir'
eloads_dir: '/path/to/eload/dir'
projects_dir: '/path/to/project/dir'
eutils_api_key: 1234556lkxflk
maven_settings_file: '/path/to/settings/file'
eva_pipeline_props: '/path/to/pipeline/properties'


genome_downloader:
  output_directory: '/path/to/reference/sequences'


executable:
  nextflow: /path/to/nextflow
  vcf_assembly_checker: /path/to/vcf_assembly_checker
  vcf_validator: /path/to/vcf_validator
  load_from_ena: /path/to/load_from_ena_script


jar:
  accession_pipeline: /path/to/accession_pipeline.jar
  eva_pipeline: /path/to/eva_pipeline.jar


biosamples:
  username: 'dsp_eva_test_user'
  password: 'dspEVAtestPwD1'
  aap_url: 'https://explore.api.aai.ebi.ac.uk/auth'
  bsd_url: 'https://wwwdev.ebi.ac.uk/biosamples'
  domain: 'subs.test-team-71'

ena:
  submit_url: https://www-test.ebi.ac.uk/ena/submit/drop-box/submit/
  ftphost: ena.example.com
  username: user
  password: pass
