eloads_dir: /usr/local/test_eva_submission/submissions/
projects_dir: /usr/local/test_eva_submission/data/

ftp_dir: /usr/local/eva/ftp/
public_ftp_dir: /usr/local/eva/public_ftp/

maven:
  environment: docker
  settings_file: /root/maven-settings.xml

genome_downloader:
  output_directory: /usr/local/eva/datasources/reference_sequences

vep_path: /usr/local/software/vep
vep_cache_path: /usr/local/eva/datasources/vep-cache

opencga_path: /usr/local/software/opencga

executable:
  md5sum: /usr/bin/md5sum
  tabix: /usr/bin/tabix
  bgzip: /usr/bin/bgzip
  bcftools: /usr/bin/bcftools
  bedtools: /usr/bin/bedtools
  samtools: /usr/bin/samtools
  minimap2: /usr/bin/minimap2
  nextflow: /usr/local/bin/nextflow
  vcf_validator: /usr/local/software/vcf_validator
  vcf_assembly_checker: /usr/local/software/vcf_assembly_checker
  python:
    interpreter: /usr/local/software/eva-submission/venv/bin/python
  submission_to_xml: /usr/local/software/mocked_eva_submission_to_xml_V1.1.0.pl
  load_from_ena: /usr/local/software/mocked_load_from_ena_postgres_or_file.pl

mongodb:
  mongo_admin_uri: mongodb://mongo_db:27017/admin
  mongo_admin_secrets_file: /root/.mongo_admin_prod_pass

jar:
  accession_pipeline: /usr/local/software/eva-accession/eva-accession-pipeline.jar
  eva_pipeline: /usr/local/software/eva-pipeline/eva-pipeline.jar
  clustering: /usr/local/software/eva-accession/eva-accession-clustering.jar
  vcf_extractor: /usr/local/software/eva-accession/eva-remapping-get-source.jar
  vcf_ingestion: /usr/local/software/eva-accession/eva-remapping-ingest.jar

eutils_api_key:

