eloads_dir: /usr/local/test_eva_submission/submissions/
projects_dir: /usr/local/test_eva_submission/submissions/

ftp_dir: /usr/local/eva/ftp/
public_ftp_dir: /usr/local/eva/public_ftp/

maven:
  environment: docker
  settings_file: /root/maven-settings.xml

genome_downloader:
  output_directory: /usr/local/eva/datasources/reference_sequences

vep_path: /usr/local/software/vep
vep_cache_path: /usr/local/eva/datasources/vep-cache

opencga_path: /usr/local/software/opencga

executable:
  md5sum: /usr/bin/md5sum
  tabix: /usr/bin/tabix
  bgzip: /usr/bin/bgzip
  bcftools: /usr/bin/bcftools
  bedtools: /usr/bin/bedtools
  samtools: /usr/bin/samtools
  minimap2: /usr/bin/minimap2
  nextflow: /usr/local/bin/nextflow
  vcf_validator: /usr/local/software/vcf_validator
  vcf_assembly_checker: /usr/local/software/vcf_assembly_checker
  python:
    interpreter: /usr/local/software/eva-submission/venv/bin/python
  submission_to_xml: /usr/local/software/mocked_eva_submission_to_xml_V1.1.0.pl
  load_from_ena: /usr/local/software/mocked_load_from_ena_postgres_or_file.pl

nextflow:
  remapping: /usr/local/software/variant-remapping/main.nf

mongodb:
  mongo_admin_uri: mongodb://mongo_db:27017/admin
  mongo_admin_secrets_file:

jar:
  accession_pipeline: /usr/local/software/eva-accession-pipeline.jar
  eva_pipeline: /usr/local/software/eva-pipeline.jar
  clustering: /usr/local/software/eva-accession-clustering.jar
  vcf_extractor: /usr/local/software/eva-remapping-get-source.jar
  vcf_ingestion: /usr/local/software/eva-remapping-ingest.jar

eutils_api_key:

ena:
  submit_url: http://eva-ws:8080/docker_mocked_services/mocked_ena/submit/drop-box/submit/
  username: docker_mock_services_user
  password: docker_mock_services_pass

