name: Trigger Eva Submission Integration Tests

on:
  push:
    branches: [master]

jobs:
  trigger-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger eva submission integration tests
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          repository: EBIvariation/eva-integration-tests
          event-type: trigger-eva-submission-tests
